services:
  php8.2:
    image: ghcr.io/staudenmeir/php:8.2
    working_dir: /var/www/html
    networks:
      - test
    volumes:
      - .:/var/www/html:delegated
      - .docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  php8.3:
    image: ghcr.io/staudenmeir/php:8.3
    working_dir: /var/www/html
    networks:
      - test
    volumes:
      - .:/var/www/html:delegated
      - .docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  php8.4:
    image: ghcr.io/staudenmeir/php:8.4
    working_dir: /var/www/html
    networks:
      - test
    volumes:
      - .:/var/www/html:delegated
      #- .docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    healthcheck:
      test: mysqladmin ping --silent
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - test
  mariadb:
    image: 'mariadb:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    networks:
      - test
  pgsql:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    networks:
      - test
  sqlsrv:
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password!
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "$${SA_PASSWORD}" -Q "SELECT 1" -b -o /dev/null
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - test
  singlestore:
    image: 'ghcr.io/singlestore-labs/singlestoredb-dev:latest'
    environment:
      # this license key is only authorized for use in SingleStore laravel-cte tests and is heavily restricted
      # if you want a free SingleStore license for your own use please visit https://www.singlestore.com/cloud-trial/
      SINGLESTORE_LICENSE: BDMwMzMyOTEyNjMwYzQ1ODE5MDdjNThiYjU1MGM5YTAyAAAAAAAAAAAEAAAAAAAAAAwwNQIZAKqnuBG9UX3K2enIHyshQGHZIjQiCZpqlwIYE8t4J8VewDLm2m4+4i8KorAIZsJd8j6EAA==
      ROOT_PASSWORD: password
    networks:
      - test
    volumes:
      - .docker/singlestore/init.sql:/init.sql
  firebird:
    image: jacobalberty/firebird:latest
    environment:
      FIREBIRD_DATABASE: 'test.fdb'
      ISC_PASSWORD: 'password'
      EnableLegacyClientAuth: 'true'
    networks:
      - test

networks:
  test:
    driver: bridge
