<?php

return [
    'mysql' => [
        'driver' => 'mysql',
        'host' => '127.0.0.1',
        'port' => getenv('MYSQL_PORT'),
        'database' => 'test',
        'username' => 'root',
        'password' => 'password',
        'unix_socket' => '',
        'charset' => 'utf8mb4',
        'collation' => 'utf8mb4_0900_ai_ci',
        'prefix' => '',
        'strict' => true,
        'engine' => null,
    ],
    'mariadb' => [
        'driver' => 'mysql',
        'host' => '127.0.0.1',
        'port' => getenv('MARIADB_PORT'),
        'database' => 'test',
        'username' => 'root',
        'password' => 'password',
        'unix_socket' => '',
        'charset' => 'utf8mb4',
        'collation' => 'utf8mb4_uca1400_ai_ci',
        'prefix' => '',
        'strict' => true,
        'engine' => null,
    ],
    'pgsql' => [
        'driver' => 'pgsql',
        'host' => '127.0.0.1',
        'port' => getenv('PGSQL_PORT'),
        'database' => 'test',
        'username' => 'postgres',
        'password' => 'password',
        'charset' => 'utf8',
        'prefix' => '',
        'search_path' => 'public',
        'sslmode' => 'prefer',
    ],
    'sqlite' => [
        'driver' => 'sqlite',
        'database' => ':memory:',
        'prefix' => '',
    ],
    'sqlsrv' => [
        'driver' => 'sqlsrv',
        'host' => '127.0.0.1',
        'port' => getenv('SQLSRV_PORT'),
        'database' => 'test',
        'username' => 'sa',
        'password' => 'Password!',
        'charset' => 'utf8',
        'prefix' => '',
        'prefix_indexes' => true,
    ],
    'singlestore' => [
        'driver' => 'singlestore',
        'host' => '127.0.0.1',
        'port' => getenv('SINGLESTORE_PORT'),
        'database' => 'test',
        'username' => 'root',
        'password' => 'test',
        'charset' => 'utf8mb4',
        'collation' => 'utf8mb4_unicode_ci',
        'prefix' => '',
        'prefix_indexes' => true,
        'strict' => true,
        'engine' => null,
        'options' => extension_loaded('pdo_mysql') ? array_filter([
            PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            PDO::ATTR_EMULATE_PREPARES => true,
        ]) : [],
    ],
];
