<?php

return [
    'mysql' => [
        'driver' => 'mysql',
        'host' => 'mysql',
        'port' => '3306',
        'database' => 'test',
        'username' => 'root',
        'password' => 'password',
        'unix_socket' => '',
        'charset' => 'utf8mb4',
        'collation' => 'utf8mb4_0900_ai_ci',
        'prefix' => '',
        'strict' => true,
        'engine' => null,
    ],
    'mariadb' => [
        'driver' => 'mariadb',
        'host' => 'mariadb',
        'port' => '3306',
        'database' => 'test',
        'username' => 'root',
        'password' => 'password',
        'unix_socket' => '',
        'charset' => 'utf8mb4',
        'collation' => 'utf8mb4_uca1400_ai_ci',
        'prefix' => '',
        'strict' => true,
        'engine' => null,
    ],
    'pgsql' => [
        'driver' => 'pgsql',
        'host' => 'pgsql',
        'port' => '5432',
        'database' => 'test',
        'username' => 'postgres',
        'password' => 'password',
        'charset' => 'utf8',
        'prefix' => '',
        'search_path' => 'public',
        'sslmode' => 'prefer',
    ],
    'sqlite' => [
        'driver' => 'sqlite',
        'database' => ':memory:',
        'prefix' => '',
    ],
    'sqlsrv' => [
        'driver' => 'sqlsrv',
        'host' => 'sqlsrv',
        'port' => '1433',
        'database' => 'test',
        'username' => 'sa',
        'password' => 'Password!',
        'charset' => 'utf8',
        'prefix' => '',
        'prefix_indexes' => true,
        'encrypt' => 'no',
    ],
    'singlestore' => [
        'driver' => 'singlestore',
        'host' => 'singlestore',
        'port' => '3306',
        'database' => 'test',
        'username' => 'root',
        'password' => 'password',
        'charset' => 'utf8mb4',
        'collation' => 'utf8mb4_unicode_ci',
        'prefix' => '',
        'prefix_indexes' => true,
        'strict' => true,
        'engine' => null,
        'options' => extension_loaded('pdo_mysql') ? array_filter([
            PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            PDO::ATTR_EMULATE_PREPARES => true,
        ]) : [],
    ],
    'firebird' => [
        'driver' => 'firebird',
        'host' => 'firebird',
        'port' => '3050',
        'database' => '/firebird/data/test.fdb',
        'username' => 'sysdba',
        'password' => 'password',
        'charset' => 'UTF8',
        'role' => null,
    ],
];
